sudo: required
language: generic
services:
  - docker

before_install:
  - docker build  -t parwinder/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true parwinder/docker-react npm run test
